CREATE TYPE "public"."share_permission" AS ENUM('view', 'edit');--> statement-breakpoint
CREATE TYPE "public"."share_status" AS ENUM('pending', 'accepted');--> statement-breakpoint
CREATE TABLE "account_shares" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_user_id" uuid NOT NULL,
	"shared_with_user_id" uuid NOT NULL,
	"permission" "share_permission" DEFAULT 'view' NOT NULL,
	"status" "share_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_shares" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "account_shares" ADD CONSTRAINT "account_shares_owner_user_id_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_shares" ADD CONSTRAINT "account_shares_shared_with_user_id_user_id_fk" FOREIGN KEY ("shared_with_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "account_shares_owner_sharee_unique" ON "account_shares" USING btree ("owner_user_id","shared_with_user_id");--> statement-breakpoint
CREATE INDEX "account_shares_sharee_idx" ON "account_shares" USING btree ("shared_with_user_id");--> statement-breakpoint
CREATE POLICY "assets_shared_select_policy" ON "assets" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "assets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "assets_shared_write_policy" ON "assets" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "assets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "assets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "budgets_shared_select_policy" ON "budgets" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "budgets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "budgets_shared_write_policy" ON "budgets" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "budgets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "budgets"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "categories_shared_select_policy" ON "categories" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "categories"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "categories_shared_write_policy" ON "categories" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "categories"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "categories"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "expenses_shared_select_policy" ON "expenses" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "expenses"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "expenses_shared_write_policy" ON "expenses" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "expenses"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "expenses"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "loans_shared_select_policy" ON "loans" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "loans"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "loans_shared_write_policy" ON "loans" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "loans"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "loans"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "savings_accounts_shared_select_policy" ON "savings_accounts" AS PERMISSIVE FOR SELECT TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "savings_accounts"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted'));--> statement-breakpoint
CREATE POLICY "savings_accounts_shared_write_policy" ON "savings_accounts" AS PERMISSIVE FOR ALL TO public USING (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "savings_accounts"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit')) WITH CHECK (EXISTS (SELECT 1 FROM account_shares WHERE account_shares.owner_user_id = "savings_accounts"."user_id" AND account_shares.shared_with_user_id = current_setting('app.current_user_id', true)::uuid AND account_shares.status = 'accepted' AND account_shares.permission = 'edit'));--> statement-breakpoint
CREATE POLICY "account_shares_select_policy" ON "account_shares" AS PERMISSIVE FOR SELECT TO public USING ("account_shares"."owner_user_id" = current_setting('app.current_user_id', true)::uuid OR "account_shares"."shared_with_user_id" = current_setting('app.current_user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "account_shares_insert_policy" ON "account_shares" AS PERMISSIVE FOR INSERT TO public WITH CHECK ("account_shares"."owner_user_id" = current_setting('app.current_user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "account_shares_update_policy" ON "account_shares" AS PERMISSIVE FOR UPDATE TO public USING ("account_shares"."owner_user_id" = current_setting('app.current_user_id', true)::uuid OR "account_shares"."shared_with_user_id" = current_setting('app.current_user_id', true)::uuid) WITH CHECK ("account_shares"."owner_user_id" = current_setting('app.current_user_id', true)::uuid OR "account_shares"."shared_with_user_id" = current_setting('app.current_user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "account_shares_delete_policy" ON "account_shares" AS PERMISSIVE FOR DELETE TO public USING ("account_shares"."owner_user_id" = current_setting('app.current_user_id', true)::uuid OR "account_shares"."shared_with_user_id" = current_setting('app.current_user_id', true)::uuid);--> statement-breakpoint
ALTER TABLE "account_shares" FORCE ROW LEVEL SECURITY;